baseURL = "https://climbusafa.com/"
languageCode = "en-us"
title = "Climb USAFA"
disableKinds = ["sitemap", "RSS", "taxonomy"]

[params]
  description = "This guidebook covers rock climbing, bouldering, ice climbing, mountain biking, skiing, highlining, trail running, and fishing in Pike National Forest bordering the U.S. Air Force Academy. Features detailed routes, maps, and information for outdoor enthusiasts in Colorado Springs."
  keywords = [
    "Climb USAFA",
    "USAFA Climbing",
    "US Air Force Academy Climbing",
    "United States Air Force Academy Climbing",
    "USAFA Adventure Guide",
    "Air Force Academy Guidebook",
    "Climbing Guidebook",
    "Outdoor Guidebook",
    "Colorado Climbing Guide",

    "Rock Climbing USAFA",
    "Bouldering USAFA",
    "Ice Climbing USAFA",
    "Mountain Biking USAFA",
    "Skiing USAFA",
    "Highlining USAFA",
    "Trail Running USAFA",
    "Fishing USAFA",
    "Pike National Forest Climbing",
    "Pike National Forest Bouldering",
    "Pike National Forest Ice Climbing",
    "Pike National Forest Mountain Biking",
    "Pike National Forest Skiing",
    "Pike National Forest Highlining",
    "Pike National Forest Trail Running",
    "Pike National Forest Fishing",

    "Colorado Springs Climbing",
    "Colorado Springs Bouldering",
    "Colorado Springs Ice Climbing",
    "Colorado Springs Mountain Biking",
    "Colorado Springs Skiing",
    "Colorado Springs Highlining",
    "Colorado Springs Trail Running",
    "Colorado Springs Fishing",
    "Pikes Peak Region Climbing",
    "Front Range Climbing",
    "Colorado Outdoor Activities",
    "Colorado Springs Outdoor Adventures",

    "Finn Westenfelder",
    "Westenfelder",
    "ISBN 979-8-21-123320-1",
    "ISBN 9798211233201",
    "979-8-21-123320-1",
    "9798211233201",
    "Book ISBN 979-8-21-123320-1",
    "Book ISBN 9798211233201",
    "Adventure Guide ISBN 979-8-21-123320-1",
    "Adventure Guide ISBN 9798211233201",

    "Mountain Project USAFA",
    "Mountain Project Air Force Academy",
    "Mountain Project Colorado Springs",
    "Mountain Project Pike National Forest",
    "USAFA Mountain Project Link",

    "USAFA Rock Climbing Guide",
    "US Air Force Academy Rock Climbing",
    "Pike National Forest Rock Climbing Routes",
    "Colorado Springs Rock Climbing Areas",
    "USAFA Outdoor Sports Guide",
    "Air Force Academy Outdoor Recreation",
    "Climbing routes USAFA",
    "Bouldering spots USAFA",
    "Ice climbing areas Colorado",
    "Mountain biking trails USAFA",
    "Skiing trails Pike National Forest",
    "Highlining spots Colorado",
    "Trail running routes Colorado Springs",
    "Fishing spots Pike National Forest",
    "USAFA outdoor activities",
    "Cadet outdoor guide",
    "Air Force Academy cadet activities",
    "Climbing near Air Force Academy",
    "Outdoor guide US Air Force Academy",
    "Adventure sports USAFA",
    "Backcountry guide USAFA",
    "Pikes Peak climbing",
    "Outdoor guide Colorado",
    "Colorado outdoor sports",
    "Finn Westenfelder author",
    "USAFA book",
    "Climb USAFA book",
    "The USAFA Adventure Guide book",
    "Free download USAFA guide",
    "Purchase USAFA guidebook",
    "USAFA climbing information",
    "Pike National Forest adventure guide",
    "Colorado Springs adventure guide",
    "Outdoor enthusiast guide USAFA",
    "Military academy outdoor guide",
    "Air Force Academy recreation",
    "Outdoor guide for Airmen",
    "USAF Academy climbing",
    "AF Academy climbing",
    "USAFA outdoor pursuits",
    "Climbing guidebook for Colorado Springs",
    "USAFA area climbing",
    "Pike Forest adventure",
    "Colorado Springs recreation guide",
    "Outdoor activities near USAFA",
    "Westenfelder climbing guide",
    "Westenfelder adventure guide",
    "USAFA free download",
    "Blurb book USAFA",
    "USAF Academy adventure",
    "USAFA hiking trails",
    "USAFA fishing spots",
    "USAFA winter sports",
    "USAFA summer activities",
    "Pike National Forest trails",
    "Colorado Springs trails",
    "Outdoor adventure in Colorado",
    "Guide to outdoor activities Colorado Springs"
  ]
